name: window_manager
description: This plugin allows Flutter desktop apps to resizing and repositioning the window.
version: 0.3.4
homepage: https://github.com/jlz139/rustdesk_window_manager

platforms:
  linux:
  macos:
  windows:

topics:
  - window
  - window resize
  - window manager
  - desktop
  - desktop window

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  screen_retriever: #^0.1.2
    git:
      url: https://github.com/jlz139/rustdesk_screen_retriever
      ref: 406b9b0

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowManagerPlugin
      macos:
        pluginClass: WindowManagerPlugin
      windows:
        pluginClass: WindowManagerPlugin
  assets:
    - images/ic_chrome_close.png
    - images/ic_chrome_maximize.png
    - images/ic_chrome_minimize.png
    - images/ic_chrome_unmaximize.png
